### ISSUE TITLE
Conflicts with ThisAssembly produced by Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by nathanwinder** [devlooped/ThisAssembly#124]
## Describe the Bug
ThisAssembly conflicts with the "ThisAssembly" generated by Nerdbank.GitVersioning
https://github.com/dotnet/Nerdbank.GitVersioning

## Steps to Reproduce

1. Reference both Nerdbank.GitVersioning and ThisAssembly.Project
```
<PackageReference Include="ThisAssembly.Project" Version="1.0.9" Condition="!Exists('packages.config')"/>
<PackageReference Include="Nerdbank.GitVersioning" Condition="!Exists('packages.config')">
  <PrivateAssets>all</PrivateAssets>
  <Version>3.5.113</Version>
</PackageReference>
```

```c#
public class ReproTest
{
  [Fact]
  public void Repro()
  {
    var fileVersion = ThisAssembly.AssemblyFileVersion; // 'ThisAssembly' does not contain a definition for 'AssemblyName'
  }
}
```

## Expected Behavior

ThisAssembly.Project should not prevent Nerbbank.GitVersioning from creating ThisAssembly properties.

## Version Info
1.0.9

**Comment by kzu** [comment]
Can't reproduce. Please attach a full failing repro. Thanks

![image](https://user-images.githubusercontent.com/169707/210148910-fa64ef02-f526-4f59-9c70-3f25dfb9a6d3.png)
[TestProject1.zip](https://github.com/devlooped/ThisAssembly/files/10327600/TestProject1.zip)
