### ISSUE TITLE
Add support for non-string constants

### ISSUE THREAD

**Issue by kzu** [devlooped/ThisAssembly#150]
### Discussed in https://github.com/devlooped/ThisAssembly/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **rdeago** May 19, 2022</sup>
I'll let code speak for me:

```xml
  <PropertyGroup>

    <!-- This still works, of course -->
    <Constant Name="Greeting" Value="Howdy!" />

    <!-- Constant type can be specified -->
    <Constant Name="Foo" Type="string" Value="Bar" />

    <!-- Int32, Integer (for the sake of VB projects) and int are all valid and map to System.Int32 -->
    <Constant Name="Answer" Type="int" Value="42" />

    <!-- Other numeric types work similarly -->
    <Constant Name="LongAnswer" Type="Int64" Value="42" />

    <!-- DateTime (and maybe TimeSpan, DateOnly, TimeOnly) may be supported too -->
    <Constant Name="BuildTime" Type="DateTime" Value="$([System.DateTime]::Now.ToString("O"))" />

  </PropertyGroup>
```

If this looks interesting, I can have a PR ready in a few days.
</div>

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Hopefully now that we have incremental generators everywhere, @rdeago can send a PR? 💯

**Comment by justinwritescode** [comment]
Can't have a const `DateTime`....it's dumb, but that's the way it is!

**Comment by kzu** [comment]
Yeah, the generator should be smart about what can be emitted as a constant vs static read only

**Comment by kzu** [comment]
I guess I'll have to work on this myself, since @rdeago hasn't sent a PR yet 😉
