### ISSUE TITLE
error SL01: SponsorLink has been incorrectly configured

### ISSUE THREAD

**Issue by CheloXL** [devlooped/ThisAssembly#210]
I installed ThisAssembly.AssemblyInfo onto one of my projects library, then I simply referencing ThisAssembly.Info.FileVersion here and there to get the .dll file version.

Now, the solution doesn't compile. It throws `CSC : error SL01: SponsorLink has been incorrectly configured. Please check the documentation for more information.`. I'm not even sure what that means, as a google search returns nothing. If I uninstall ThisAssembly, everything goes back to normal.

Any ideas?

**Comment by kzu** [comment]
Seems like an incomplete nuget restore. Closing/reopening the solution should fix, could you try that?

**Comment by CheloXL** [comment]
That was my first though and I even did a `dotnet restore soluction.sln --force`. It doesn't work.
What I see is that the error is reported on projects that are using ThisAssembly through a project reference. So, basically, I have project A that have the package installed, and project B references project A and uses ThisAssembly. The error is reported on project B.
I want to do so because I'm interested in the information of project A to be shown on project B (A is the business project, B is a webapp that uses/exposes the business).

**Comment by kzu** [comment]
Awesome description to come up with a repro. Thanks for elaborating! Will take a closer look with that in mind...

**Comment by kzu** [comment]
Ok, there are two unrelated but relevant issues. First: if you add `PrivateAssets=all` the the package reference to ThisAssembly, the error should go away in the transitive protect. The other issue is SponsorLink related due to the non-transitive build targets.

Thanks a lot for the report! Will ship a fix ASAP
