### ISSUE TITLE
Fails for assembly metadata containing `.`

### ISSUE THREAD

**Issue by Khitiara** [devlooped/ThisAssembly#247]
## Describe the Bug

AssemblyMetadata attributes whose keys include the `.` characte those generate into invalid constant names and produce compiler errors.

## Steps to Reproduce

```c#
[assembly: System.Reflection.AssemblyMetadata("A.B", "")]
[assembly: System.Reflection.AssemblyMetadata("A.C", "")]
```

## Expected Behavior

Compilation to succeed.

## Version Info

ThisAssembly 1.3.1

## Additional Info

Discovered when using [Verify](https://github.com/VerifyTests/Verify) which generates a few such metadata attributes during build

**Comment by kzu** [comment]
Consider sponsoring [@devlooped](https://github.com/sponsors/devlooped) to bump the priority of this. 

Otherwise, we'd gladly take a PR!

**Comment by dmirmilshteyn** [comment]
This problem also causes a failure when you include the sentry.io SDK, since that adds a `Senry.ProjectDirectory` AssemblyMetadata attribute.

**Comment by kzu** [comment]
Happy to take a PR 👌
