### ISSUE TITLE
ThisAssembly.Resources causes IL3000 warnings when publishing for AOT compilation in .NET 8

### ISSUE THREAD

**Issue by atifaziz** [devlooped/ThisAssembly#279]
## Describe the Bug

Using **ThisAssembly.Resources** to access resources produces [IL3000](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(IL3000)%26rd%3Dtrue) warning when published for AOT compilation using .NET 8. This is caused by the following code in `EmbeddedResource` that gets embedded into the user project:

https://github.com/devlooped/ThisAssembly/blob/0e5f0c46eb3950fc0fdca3db9bdbba635a379e88/src/EmbeddedResource.cs#L8

It looks like that this is done to give an external file preference over the embedded resource (which is a surprising behaviour that should really be opted into via some option):

https://github.com/devlooped/ThisAssembly/blob/0e5f0c46eb3950fc0fdca3db9bdbba635a379e88/src/EmbeddedResource.cs#L27-L29

## Steps to Reproduce

These steps assume .NET SDK 8 is in use.

1. Run `dotnet new console` to create a new console project
2. Run `dotnet add package ThisAssembly.Resources` to add a reference to the **ThisAssembly.Resources** package.
3. Add a resource to the project.
4. Add the `<PublishAot>true</PublishAot>` property to the project file.
5. Publish with `dotnet publish -c Release -o dist`

During compilation, the following warning is emitted:

    ThisAssembly.Resource\ThisAssembly.ResourcesGenerator\ThisAssembly.Resources.EmbeddedResource.cs(8): warning IL3000: EmbeddedResource..cctor(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.

A fully working example can be found in [`ThisAssemblyApp.zip`](https://github.com/devlooped/ThisAssembly/files/13850635/ThisAssemblyApp.zip).

## Expected Behavior

- Expected no warnings during `dotnet publish` when doing AOT compilation.
- Embedded resources are unaffected by files on disk.
Of course, if the user project is treating warnings as errors then the compilation entirely fails. It is awkward, if not possible impossible, to isolate the suppression of IL3000 to just the generated code (since it doesn't technically exist on disk).

## Version Info

Using [version 1.41 of the package](https://www.nuget.org/packages/ThisAssembly.Resources/1.4.1).

## Additional Info

Running `dotnet --info` prints:

    .NET SDK:
     Version:           8.0.100
     Commit:            57efcf1350
     Workload version:  8.0.100-manifests.6a1e483a

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.22621
     OS Platform: Windows
     RID:         win-x64
     Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

    .NET workloads installed:
     Workload version: 8.0.100-manifests.6a1e483a
     [wasm-tools]
       Installation Source: VS 17.8.34330.188
       Manifest Version:    8.0.0/8.0.100
       Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.0\WorkloadManifest.json
       Install Type:              Msi

    Host:
      Version:      8.0.0
      Architecture: x64
      Commit:       5535e31a71

    .NET SDKs installed:
      3.1.426 [C:\Program Files\dotnet\sdk]
      5.0.416 [C:\Program Files\dotnet\sdk]
      6.0.417 [C:\Program Files\dotnet\sdk]
      7.0.203 [C:\Program Files\dotnet\sdk]
      7.0.404 [C:\Program Files\dotnet\sdk]
      8.0.100 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
      Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Other architectures found:
      x86   [C:\Program Files (x86)\dotnet]
        registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

    Environment variables:
      Not set

    global.json file:
      T:\ThisAssemblyApp\global.json

    Learn more:
      https://aka.ms/dotnet/info

    Download .NET:
      https://aka.ms/dotnet/download

**Comment by kzu** [comment]
Shipped in https://github.com/devlooped/ThisAssembly/releases/tag/v1.4.3
