### ISSUE TITLE
ThisAssembly is unusable in old-style NetFX projects. error CS0122: 'ThisAssembly' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ShadowMarker789** [devlooped/ThisAssembly#301]
## Describe the Bug

In old-style NetFX WPF csproj projects, any attempt to reference ThisAssembly, even typeof(ThisAssembly) will not compile. 

error CS0122: 'ThisAssembly' is inaccessible due to its protection level

## Steps to Reproduce

In an old-style NetFX WPF csproj C# file, any references to ThisAssembly will not compile. 

```c#
public class ReproTest
{
  [Fact]
  public void Repro()
  {
    var branchName = ThisAssembly.Git.Branch; // this won't compile. 
  }
}
```

## Expected Behavior

The expectations were that this would compile. 

## Exception with Stack Trace

No exception, only a build error placed above. 

## Version Info

1.4.3 via Nuget 

## Additional Info

Related issues possibly

https://github.com/dotnet/Nerdbank.GitVersioning/issues/404

https://github.com/dotnet/Nerdbank.GitVersioning/issues/449

**Comment by kzu** [comment]
From https://github.com/microsoft/CsWin32/issues/7, is it fixed when you set this property?

```xml
<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
```

**Comment by kzu** [comment]
Converting the project to SDK-style fixes the issue. I took a clean .NET WPF app from the template, removed all the relevant stuff and with the following content, it works:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <UseWPF>true</UseWPF>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xaml">
      <RequiredTargetFramework>4.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ThisAssembly" Version="1.4.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
```

Legacy projects are unlikely to be supported, but I'd take a PR that adds it.
