### ISSUE TITLE
Add ThisAssembly.Git

### ISSUE THREAD

**Issue by kzu** [devlooped/ThisAssembly#69]
This is something that [GitInfo](https://github.com/devlooped/GitInfo) provides, but it does so using MSBuild and it seems to cause [an issue in some source-generator scenarios](https://github.com/devlooped/GitInfo/issues/104).

So perhaps it would be best if the codegen part was provided by a source generator in this project instead, with GitInfo detecting its presence (via a ThisAssemblyGitInfo=true property perhaps?) and avoid generating the `ThisAssembly.Git` part of the code.

It might even make sense for GitInfo to take a dependency on the new `ThisAssembly.Git` entirely and just augment it for the semver determination.

This implementation should likely rely on SourceLink implementation for some information retrieval, and take a dependency on it to avoid duplicating work?

**Comment by viceroypenguin** [comment]
The biggest problem with doing this as a source generator is that SG should not do I/O (in fact, recommendation is that no SG should take more than 10ms to complete). Getting git info would require doing I/O to open the files .git uses to read the data it needs. Recommend that the current path (build task in GitInfo) is the proper way to do this.

**Comment by kzu** [comment]
SourceLink already populates most (all?) of the information GitInfo calculates. So perhaps it's mostly just exposing those to .NET code...

**Comment by viceroypenguin** [comment]
To make sure I understand: the SG would not store the values, simply the code that access the data present in the SourceLink area?
