### ISSUE TITLE
Exception when typing out AssemblyInformationalVersion

### ISSUE THREAD

**Issue by KirillOsenkov** [devlooped/ThisAssembly#77]
## Describe the Bug

When typing `[assembly: AssemblyInformationalVersion]` in the editor, there's an exception in here:
https://github.com/devlooped/ThisAssembly/blob/b83a3dff877b21a2ad40c1abd8076a1826ddb442/src/ThisAssembly.AssemblyInfo/AssemblyInfoGenerator.cs#L34
because the constructor arguments is empty. And as far as I can tell the generator gets turned off after the exception and stops working.

## Version Info

1.0.8

**Comment by kzu** [comment]
ugh... thanks for reporting!!
